/* @author VGSG */

public class MDI extends javax.swing.JFrame {

    /**
     * Creates new form MDI
     */
    public MDI() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuempleados = new javax.swing.JMenu();
        itmAddEmp = new javax.swing.JMenuItem();
        itmListarEmp = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        mnumesas = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bar");
        setResizable(false);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 814, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
        );

        mnuempleados.setText("Empleados");

        itmAddEmp.setText("Agregar nuevo");
        itmAddEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAddEmpActionPerformed(evt);
            }
        });
        mnuempleados.add(itmAddEmp);

        itmListarEmp.setText("Listar");
        itmListarEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmListarEmpActionPerformed(evt);
            }
        });
        mnuempleados.add(itmListarEmp);

        jMenuItem3.setText("Eliminar");
        mnuempleados.add(jMenuItem3);

        jMenuBar1.add(mnuempleados);

        jMenu2.setText("Meseros");

        jMenuItem4.setText("Agregar");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Eliminar");
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Asignar");
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        mnumesas.setText("Mesas");

        jMenuItem7.setText("Agregar");
        mnumesas.add(jMenuItem7);

        jMenuItem8.setText("Eliminar");
        mnumesas.add(jMenuItem8);

        jMenuItem9.setText("Listar");
        mnumesas.add(jMenuItem9);

        jMenuBar1.add(mnumesas);

        jMenu3.setText("Ventas");

        jMenuItem10.setText("Listar");
        jMenu3.add(jMenuItem10);

        jMenuItem11.setText("Aclaraciones/Cancelaciones");
        jMenu3.add(jMenuItem11);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Productos");

        jMenuItem14.setText("Agregar");
        jMenu1.add(jMenuItem14);

        jMenuItem15.setText("Llstar");
        jMenu1.add(jMenuItem15);

        jMenuItem16.setText("Modificar");
        jMenu1.add(jMenuItem16);

        jMenuItem17.setText("Eliminar");
        jMenu1.add(jMenuItem17);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Corte de caja");

        jMenuItem12.setText("Barra");
        jMenu4.add(jMenuItem12);

        jMenuItem13.setText("Cocina");
        jMenu4.add(jMenuItem13);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmAddEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAddEmpActionPerformed
        AddEmpleado frame = new AddEmpleado();
        if(!frame.isShowing()){
            escritorio.add(frame);
            frame.show();
        }
    }//GEN-LAST:event_itmAddEmpActionPerformed

    private void itmListarEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmListarEmpActionPerformed
        ListarEmpleados frame = new ListarEmpleados();
        if(!frame.isShowing()){
            escritorio.add(frame);
            frame.show();
        }
    }//GEN-LAST:event_itmListarEmpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem itmAddEmp;
    private javax.swing.JMenuItem itmListarEmp;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu mnuempleados;
    private javax.swing.JMenu mnumesas;
    // End of variables declaration//GEN-END:variables
}
